// Generated by `bun init`

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.png" {
  const path: `${string}.png`;
  export = path;
}

declare module "*.avif" {
  const path: `${string}.avif`;
  export = path;
}

declare module "*.wav" {
  const path: `${string}.wav`;
  export = path;
}

declare module "*.ogg" {
  const path: `${string}.ogg`;
  export = path;
}

declare module "*.woff2" {
  const path: `${string}.woff2`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}
