export { default as f552 } from "../../assets/frames_compressed/552.avif";
export { default as f556 } from "../../assets/frames_compressed/556.avif";
export { default as f560 } from "../../assets/frames_compressed/560.avif";
export { default as f563 } from "../../assets/frames_compressed/563.avif";
export { default as f567 } from "../../assets/frames_compressed/567.avif";
export { default as f571 } from "../../assets/frames_compressed/571.avif";
export { default as f575 } from "../../assets/frames_compressed/575.avif";
export { default as f578 } from "../../assets/frames_compressed/578.avif";
export { default as f582 } from "../../assets/frames_compressed/582.avif";
